# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: nndmovie
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  elasticsearch:
    extends:
      file: ./elasticsearch.yml
      service: elasticsearch
  redis:
    extends:
      file: ./redis.yml
      service: redis
