package com.nndmove.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GenresAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenresAllPropertiesEquals(Genres expected, Genres actual) {
        assertGenresAutoGeneratedPropertiesEquals(expected, actual);
        assertGenresAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenresAllUpdatablePropertiesEquals(Genres expected, Genres actual) {
        assertGenresUpdatableFieldsEquals(expected, actual);
        assertGenresUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenresAutoGeneratedPropertiesEquals(Genres expected, Genres actual) {
        assertThat(expected)
            .as("Verify Genres auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenresUpdatableFieldsEquals(Genres expected, Genres actual) {
        assertThat(expected)
            .as("Verify Genres relevant properties")
            .satisfies(e -> assertThat(e.getGenres()).as("check genres").isEqualTo(actual.getGenres()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenresUpdatableRelationshipsEquals(Genres expected, Genres actual) {
        assertThat(expected)
            .as("Verify Genres relationships")
            .satisfies(e -> assertThat(e.getMovies()).as("check movies").isEqualTo(actual.getMovies()));
    }
}
