package com.nndmove.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PremiumAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPremiumAllPropertiesEquals(Premium expected, Premium actual) {
        assertPremiumAutoGeneratedPropertiesEquals(expected, actual);
        assertPremiumAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPremiumAllUpdatablePropertiesEquals(Premium expected, Premium actual) {
        assertPremiumUpdatableFieldsEquals(expected, actual);
        assertPremiumUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPremiumAutoGeneratedPropertiesEquals(Premium expected, Premium actual) {
        assertThat(expected)
            .as("Verify Premium auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPremiumUpdatableFieldsEquals(Premium expected, Premium actual) {
        assertThat(expected)
            .as("Verify Premium relevant properties")
            .satisfies(e -> assertThat(e.getStartDate()).as("check startDate").isEqualTo(actual.getStartDate()))
            .satisfies(e -> assertThat(e.getEndDate()).as("check endDate").isEqualTo(actual.getEndDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPremiumUpdatableRelationshipsEquals(Premium expected, Premium actual) {}
}
